apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: vela-app
  namespace: local-gitops
spec:
  components:
    - name: server
      type: webservice
      properties:
        image: nginx
